"""initial RFQ schema

Revision ID: 1be84c2ab16c
Revises: 
Create Date: 2026-09-28 16:24:39.965522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be84c2ab16c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('selected_sheet', sa.String(length=255), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=True),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('warning_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('created_by_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_import_type'), 'import_batches', ['import_type'], unique=False)
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_table('parts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fcl_part_code', sa.String(length=100), nullable=False),
    sa.Column('canonical_description', sa.Text(), nullable=False),
    sa.Column('normalized_description', sa.Text(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcl_part_code')
    )
    op.create_index('ix_parts_normalized_description_prefix', 'parts', ['normalized_description'], unique=False, mysql_length=255)
    op.create_table('part_aliases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.BigInteger(), nullable=False),
    sa.Column('alias_text', sa.Text(), nullable=False),
    sa.Column('normalized_alias', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'normalized_alias', name='uq_part_alias_normalized')
    )
    op.create_index(op.f('ix_part_aliases_part_id'), 'part_aliases', ['part_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fcl_enquiry_no', sa.String(length=100), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('customer_id_ref', sa.String(length=100), nullable=True),
    sa.Column('customer_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('industry_type', sa.String(length=100), nullable=True),
    sa.Column('request_from', sa.String(length=100), nullable=True),
    sa.Column('sales_person_ref', sa.String(length=100), nullable=True),
    sa.Column('assigned_engineer_ref', sa.String(length=100), nullable=True),
    sa.Column('rd_review_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('requirement_type', sa.String(length=50), nullable=True),
    sa.Column('ga_drawing_status', sa.String(length=50), nullable=True),
    sa.Column('bought_out_request_status', sa.String(length=50), nullable=True),
    sa.Column('bought_out_quotation_status', sa.String(length=50), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('import_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcl_enquiry_no')
    )
    op.create_index(op.f('ix_rfqs_assigned_engineer_ref'), 'rfqs', ['assigned_engineer_ref'], unique=False)
    op.create_index(op.f('ix_rfqs_customer_id_ref'), 'rfqs', ['customer_id_ref'], unique=False)
    op.create_index(op.f('ix_rfqs_customer_name_snapshot'), 'rfqs', ['customer_name_snapshot'], unique=False)
    op.create_index(op.f('ix_rfqs_import_batch_id'), 'rfqs', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_rfqs_sales_person_ref'), 'rfqs', ['sales_person_ref'], unique=False)
    op.create_index(op.f('ix_rfqs_source'), 'rfqs', ['source'], unique=False)
    op.create_index(op.f('ix_rfqs_status'), 'rfqs', ['status'], unique=False)
    op.create_table('staged_import_rows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('normalized_data', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('validation_messages', sa.JSON(), nullable=True),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('normalized_description', sa.Text(), nullable=True),
    sa.Column('suggested_part_id', sa.BigInteger(), nullable=True),
    sa.Column('match_type', sa.String(length=30), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confirmed_part_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['confirmed_part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['suggested_part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'row_number', name='uq_staged_batch_row')
    )
    op.create_index(op.f('ix_staged_import_rows_batch_id'), 'staged_import_rows', ['batch_id'], unique=False)
    op.create_index(op.f('ix_staged_import_rows_validation_status'), 'staged_import_rows', ['validation_status'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rfq_id', sa.BigInteger(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('adjustment_data', sa.JSON(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfq_id', 'revision_number', name='uq_quotation_rfq_revision')
    )
    op.create_index(op.f('ix_quotations_rfq_id'), 'quotations', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_table('rfq_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rfq_id', sa.BigInteger(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('original_item_description', sa.Text(), nullable=False),
    sa.Column('normalized_description', sa.Text(), nullable=True),
    sa.Column('matched_part_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_part_code', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quoted_unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('match_status', sa.String(length=50), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfq_id', 'line_number', name='uq_rfq_line_number')
    )
    op.create_index(op.f('ix_rfq_items_matched_part_id'), 'rfq_items', ['matched_part_id'], unique=False)
    op.create_index(op.f('ix_rfq_items_rfq_id'), 'rfq_items', ['rfq_id'], unique=False)
    op.create_table('rfq_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rfq_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_ref', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_status_history_changed_at'), 'rfq_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_rfq_status_history_rfq_id'), 'rfq_status_history', ['rfq_id'], unique=False)
    op.create_table('quotation_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.BigInteger(), nullable=False),
    sa.Column('rfq_item_id', sa.BigInteger(), nullable=False),
    sa.Column('part_id', sa.BigInteger(), nullable=True),
    sa.Column('description_snapshot', sa.Text(), nullable=False),
    sa.Column('fcl_part_code_snapshot', sa.String(length=100), nullable=True),
    sa.Column('quantity_snapshot', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['rfq_item_id'], ['rfq_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_quotation_items_rfq_item_id'), 'quotation_items', ['rfq_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_items_rfq_item_id'), table_name='quotation_items')
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_index(op.f('ix_rfq_status_history_rfq_id'), table_name='rfq_status_history')
    op.drop_index(op.f('ix_rfq_status_history_changed_at'), table_name='rfq_status_history')
    op.drop_table('rfq_status_history')
    op.drop_index(op.f('ix_rfq_items_rfq_id'), table_name='rfq_items')
    op.drop_index(op.f('ix_rfq_items_matched_part_id'), table_name='rfq_items')
    op.drop_table('rfq_items')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_rfq_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_staged_import_rows_validation_status'), table_name='staged_import_rows')
    op.drop_index(op.f('ix_staged_import_rows_batch_id'), table_name='staged_import_rows')
    op.drop_table('staged_import_rows')
    op.drop_index(op.f('ix_rfqs_status'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_source'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_sales_person_ref'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_import_batch_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_customer_name_snapshot'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_customer_id_ref'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_assigned_engineer_ref'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index(op.f('ix_part_aliases_part_id'), table_name='part_aliases')
    op.drop_table('part_aliases')
    op.drop_index('ix_parts_normalized_description_prefix', table_name='parts', mysql_length=255)
    op.drop_table('parts')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_import_type'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
